name: Verificacion Basica

on:
  push:
    branches:
      - main

jobs:
  verificar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Verificar archivo index.html
        run: test -f index.html

      - name: Mensaje de validacion
        run: echo "Proyecto validado correctamente"